#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{log/nginx,keys,log/php} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx

# create local php.ini, set local timezone
printf "; Edit this file to override php.ini directives and restart the container\\n\\ndate.timezone = %s\\n" "$TZ" > /etc/php7/conf.d/php-local.ini
#fix php-fpm log location
sed -i "s#;error_log = log/php7/error.log.*#error_log = /config/log/php/error.log#g" /etc/php7/php-fpm.conf
#fix php-fpm user
sed -i "s#user = nobody.*#user = abc#g" /etc/php7/php-fpm.d/www.conf
sed -i "s#group = nobody.*#group = abc#g" /etc/php7/php-fpm.d/www.conf

# backwards compatibility for alpine >=3.14
if [ ! -e /etc/nginx/conf.d ]; then
    ln -s /etc/nginx/http.d /etc/nginx/conf.d
fi

# permissions
chown -R abc:abc \
    /config \
    /var/lib/nginx \
    /var/tmp/nginx
chmod -R 644 /etc/logrotate.d
